---

dockerhub_login_vault: "{{ dockerhub_login }}"

dockerhub_pwd_vault: "{{ dockerhub_pwd }}"

home: "/home/ubuntu"

phonebook_source_branch: "main"


repo_phonebook: "git@github.com:carollebertille/phonebook-dev.git"

tag_version: "v1.0"

branch_clone: "main"

address_public_preprod: "54.198.56.195"

adresse_preprod: "172.31.36.38"

port_preprod: "8181"







