---
repo_phonebook: "https://github.com/carollebertille/phonebook-dev.git"
source_branch: "develop"
image_tag: "0.2"

home: "/home/ubuntu"


ip_addr_preprod: "54.164.149.48 "
ip_addr_prod: "52.91.127.130"
port_app: "8181"

#secret data vaulted
dockerhub_login_vault: "{{ dockerhub_login }}"

dockerhub_pwd_vault: "{{ dockerhub_pwd }}"







